config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.com/fall3d-suite/fall3d-gpu:
      branch: feature-badge
      repo: https://gitlab.com/fall3d-suite/fall3d-gpu
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.com/fall3d-suite/fall3d-gpu git:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-maroon-bird.sh
        container: qc.acc_sunny-burgundy-gerbil
  QC.Doc:
    repos:
      gitlab.com/fall3d-suite/fall3d-gpu find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-taupe-avocet.sh
        container: qc.doc_chewy-azure-lionfish
      gitlab.com/fall3d-suite/fall3d-gpu git:
        commands:
        - /usr/bin/env sh .sqa/script.messy-gold-horse.sh
        container: qc.doc_pasty-corn-lionfish
      gitlab.com/fall3d-suite/fall3d-gpu markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-olive-warthog.sh
        container: qc.doc_squirrely-grey-cuscus
  QC.Lic:
    repos:
      gitlab.com/fall3d-suite/fall3d-gpu licensee:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-celadon-meerkat.sh
        container: qc.lic_scummy-puce-tang
  QC.Met:
    repos:
      gitlab.com/fall3d-suite/fall3d-gpu cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-pink-swan.sh
        container: qc.met_breezy-harlequin-barnacle
  QC.Sec:
    repos:
      gitlab.com/fall3d-suite/fall3d-gpu bandit:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-goldenrod-moose.sh
        container: qc.sec_shabby-vermilion-oyster
  QC.Sty:
    repos:
      gitlab.com/fall3d-suite/fall3d-gpu flake8:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-pumpkin-chow.sh
        container: qc.sty_crappy-mustard-lobster
  QC.Ver:
    repos:
      gitlab.com/fall3d-suite/fall3d-gpu get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-amber-blue.sh
        container: qc.ver_pokey-asparagus-wolf
timeout: 5400
