config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.com/fall3d-suite/fall3d-gpu:
      branch: master
      repo: https://gitlab.com/fall3d-suite/fall3d-gpu
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.com/fall3d-suite/fall3d-gpu git:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-cream-hamster.sh
        container: qc.acc_flimsy-buff-bongo
  QC.Doc:
    repos:
      gitlab.com/fall3d-suite/fall3d-gpu find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.ready-indigo-budgerigar.sh
        container: qc.doc_beady-green-bordeaux
      gitlab.com/fall3d-suite/fall3d-gpu git:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-bronze-akbash.sh
        container: qc.doc_lumpy-indigo-antelope
  QC.Lic:
    repos:
      gitlab.com/fall3d-suite/fall3d-gpu licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-asparagus-caracal.sh
        container: qc.lic_whiny-periwinkle-retriever
  QC.Sec:
    repos:
      gitlab.com/fall3d-suite/fall3d-gpu bandit:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-celadon-monster.sh
        container: qc.sec_pretty-blue-lionfish
  QC.Sty:
    repos:
      gitlab.com/fall3d-suite/fall3d-gpu flake8:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-ochre-sheepdog.sh
        container: qc.sty_hasty-wisteria-meerkat
  QC.Ver:
    repos:
      gitlab.com/fall3d-suite/fall3d-gpu get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-chartreuse-horse.sh
        container: qc.ver_shaky-olivine-bloodhound
timeout: 5400
