config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.com/fall3d-suite/fall3d-gpu:
      branch: feature-badge
      repo: https://gitlab.com/fall3d-suite/fall3d-gpu
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.com/fall3d-suite/fall3d-gpu git:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-tomato-stoat.sh
        container: qc.acc_bluesy-vermilion-beaver
  QC.Doc:
    repos:
      gitlab.com/fall3d-suite/fall3d-gpu find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-olivine-goat.sh
        container: qc.doc_zippy-yellow-pig
      gitlab.com/fall3d-suite/fall3d-gpu git:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-grey-tzu.sh
        container: qc.doc_skimpy-yellow-orangutan
      gitlab.com/fall3d-suite/fall3d-gpu markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-saffron-dodo.sh
        container: qc.doc_droopy-goldenrod-blue
  QC.Lic:
    repos:
      gitlab.com/fall3d-suite/fall3d-gpu licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-cardinal-fish.sh
        container: qc.lic_silly-ivory-spaniel
  QC.Met:
    repos:
      gitlab.com/fall3d-suite/fall3d-gpu cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-alizarin-setter.sh
        container: qc.met_nippy-ecru-vole
  QC.Sec:
    repos:
      gitlab.com/fall3d-suite/fall3d-gpu bandit:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-peach-skunk.sh
        container: qc.sec_stinky-auburn-bullfrog
  QC.Sty:
    repos:
      gitlab.com/fall3d-suite/fall3d-gpu flake8:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-cerise-tarantula.sh
        container: qc.sty_goopy-white-ferret
  QC.Ver:
    repos:
      gitlab.com/fall3d-suite/fall3d-gpu get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-malachite-cuscus.sh
        container: qc.ver_ugly-cardinal-owl
timeout: 5400
