config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.com/fall3d-suite/fall3d-gpu:
      branch: feature-badge
      repo: https://gitlab.com/fall3d-suite/fall3d-gpu
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.com/fall3d-suite/fall3d-gpu git:
        commands:
        - /usr/bin/env sh .sqa/script.homely-thistle-bison.sh
        container: qc.acc_sunny-lemon-corgi
  QC.Doc:
    repos:
      gitlab.com/fall3d-suite/fall3d-gpu find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-ecru-drever.sh
        container: qc.doc_sloppy-tangerine-harrier
      gitlab.com/fall3d-suite/fall3d-gpu git:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-periwinkle-cuttlefish.sh
        container: qc.doc_clammy-goldenrod-affenpinscher
      gitlab.com/fall3d-suite/fall3d-gpu markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-linen-koala.sh
        container: qc.doc_scaly-carmine-barracuda
  QC.Lic:
    repos:
      gitlab.com/fall3d-suite/fall3d-gpu licensee:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-cornflower-neanderthal.sh
        container: qc.lic_beady-magnolia-ant
  QC.Met:
    repos:
      gitlab.com/fall3d-suite/fall3d-gpu cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-cobalt-boar.sh
        container: qc.met_hazy-amber-wrasse
  QC.Sec:
    repos:
      gitlab.com/fall3d-suite/fall3d-gpu bandit:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-cerise-mouse.sh
        container: qc.sec_foggy-sapphire-havanese
  QC.Sty:
    repos:
      gitlab.com/fall3d-suite/fall3d-gpu flake8:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-mustard-pig.sh
        container: qc.sty_lovely-jade-moose
  QC.Ver:
    repos:
      gitlab.com/fall3d-suite/fall3d-gpu get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-ochre-shark.sh
        container: qc.ver_wimpy-gamboge-giraffe
timeout: 5400
